version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-tdd
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ID}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS} # 비밀번호에 특수문자 사용 X
    volumes:
      - ./mongodb-data:/data/db
  mongo-express: # 웹 브라우저에서 모니터링할 수 있게 해줌
    image: mongo-express:latest
    container_name: mongo-express-tdd
    restart: always # mongo가 켜지기 전에 실행되면 에러가 나기 때문에 다시 연결
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_ID}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS} # 기본은 admin, pass
      - ME_CONFIG_BASICAUTH_USERNAME=${DB_ID}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DB_PASS} # 이렇게 해주면 내 설정으로 접속 가능
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_ID}:${DB_PASS}@mongodb:27017
      # ME_CONFIG_MONGODB_SERVER 기본 값은 'mongo' 임 그래서 자꾸 에러나는듯 ? URL을 설정해주자!